ALTER DATABASE `mmaz` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE mmaz;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    ID INT(4) AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL
);
INSERT INTO USERS(NAME, SURNAME) VALUES ('Jan','Kowalski');
INSERT INTO USERS(NAME, SURNAME) VALUES ('Janina','Kowalski');
INSERT INTO USERS(NAME, SURNAME) VALUES ('Adam','Tomaszewicz');
INSERT INTO USERS(NAME, SURNAME) VALUES ('Tomasz','Brzęczyszczykiewicz');